### ISSUE TITLE
Help, please!

### ISSUE THREAD

**Issue by Warrior562** [optiv/Dent#2]
Hello, first of all thanks for this amazing tool developed!
I need help with this quote of you : 
`Once generated, copy line 13 and 14 from the outputted file, and merge them together, making sure to remove:

the var <variable name>
the ; at the end of each line
the quotes around each string`

Imagine my output content of line 13 and 14 is this one : 

`var mJBYWp = 'KDSKASDKAJKDJSAJSJKAKJKDS';
var hkfkakdskak = 'JSADIISAIDISAKSAKDKSAKSAIU';`

Correct output will be this one ? : 

`KDSKASDKAJKDJSAJSJKAKJKDSJSADIISAIDISAKSAKDKSAKSAIU`

on line 13 & 14 ?

Thanks.

**Comment by Warrior562** [comment]
![Captura](https://user-images.githubusercontent.com/85058177/120106773-b1435a80-c15e-11eb-88ca-642136919d1a.PNG)

**Comment by Warrior562** [comment]
Correct Output will be 

TVq.......................................................................................................MOGAH.............................=     This is the correct one?

**Comment by Tylous** [comment]
so lines 13 and 14 make up the entire base64 string you need them both in order to. So you would need the entire output of line 13 (which should be a very long string) and then add the contents of line 14 to the end of line 13. Does that make sense?

**Comment by Warrior562** [comment]
@Tylous Thanks for your reply!
